import AdmZip from "adm-zip";
import type { AssetRecord } from "@/db/schema";
import type { ProjectRecord } from "@/db/schema";
import { analysisFromAssetRow } from "@/lib/analysis-from-record";
import { generateDataProduct } from "@/lib/data-product";
import { buildMigrationPdf, type PdfBranding } from "@/lib/pdf";
import type { AnalysisResult, DataProductBlueprint } from "@/lib/types";

function resolveBlueprint(asset: AssetRecord, analysis: AnalysisResult): DataProductBlueprint {
  const fresh = generateDataProduct(analysis);
  if (!asset.blueprintJson) return fresh;
  try {
    const parsed = JSON.parse(asset.blueprintJson) as Partial<DataProductBlueprint>;
    return {
      ...fresh,
      ...parsed,
      semanticMappings:
        parsed.semanticMappings && parsed.semanticMappings.length > 0
          ? parsed.semanticMappings
          : fresh.semanticMappings,
      datasphereJson: parsed.datasphereJson ?? fresh.datasphereJson,
    };
  } catch {
    return fresh;
  }
}

function buildClientReadme(params: {
  asset: AssetRecord;
  project: ProjectRecord | null;
  analysis: AnalysisResult;
  generatedAt: string;
}): string {
  const { asset, project, analysis, generatedAt } = params;
  const client = project ? `${project.clientName} (${project.projectCode})` : "—";
  const consultant = project?.consultantOwner ?? "—";

  return `# BDC Pulse — Consulting Deliverable Package

**SAC → SAP Business Data Cloud Migration Assessment**

---

## Engagement summary

| Field | Value |
|-------|--------|
| **Asset** | ${asset.name} |
| **Asset ID** | ${asset.id} |
| **Client / project** | ${client} |
| **Consultant owner** | ${consultant} |
| **Generated (UTC)** | ${generatedAt} |
| **Migration Readiness Score** | **${analysis.score}%** (${analysis.effort} effort) |
| **Scoring engine** | ${analysis.scoringEngineVersion ?? "—"} |
| **Parser** | ${analysis.parserEngineVersion ?? "—"} |
| **LLM narrative** | ${analysis.llmUnavailable ? "Not used — rules-only assessment" : "Included where configured"} |

---

## Package contents

| File | Description |
|------|-------------|
| \`executive-report.pdf\` | Executive PDF report — readiness score, pillars, semantic translation highlights, findings, and disclaimer |
| \`semantic-translation-log.json\` | Full SAC → BDC/Datasphere pattern mapping with justifications and recommendations |
| \`score-breakdown-and-pillars.json\` | Weighted pillar scores (25/25/20/15/15) and deterministic score audit trail |
| \`data-product-blueprint.json\` | Datasphere-oriented blueprint: fact/dimension views, hierarchies, associations, semantic mappings |
| \`portfolio-snapshot.json\` | Structured analysis snapshot for tooling or workshop import |

---

## How to use this package

1. **Workshop kickoff** — Open \`executive-report.pdf\` with business and IT stakeholders.
2. **Technical deep dive** — Review \`semantic-translation-log.json\` with your SAC/BDC architects.
3. **Solution design** — Adapt \`data-product-blueprint.json\` into your SAP Datasphere / BDC target architecture.
4. **Governance** — Reference \`score-breakdown-and-pillars.json\` to explain how the readiness score was derived.

---

## Important notice

Scores and semantic mappings are produced by a **deterministic, versioned rule engine** from SAC export JSON. They accelerate assessment and design — they are **not** a guarantee of migration outcome, timeline, licensing, or cost. Validate all mappings in workshops and against official SAP product documentation.

*Generated by [BDC Pulse](https://github.com/sypherdark/BDC-Pulse) — SAC to SAP Business Data Cloud Migration Accelerator.*
`;
}

export async function buildConsultingExportZip(params: {
  asset: AssetRecord;
  project: ProjectRecord | null;
  branding: PdfBranding;
}): Promise<{ buffer: Buffer; filename: string }> {
  const { asset, project, branding } = params;
  const analysis = analysisFromAssetRow(asset);
  const blueprint = resolveBlueprint(asset, analysis);
  const generatedAt = new Date().toISOString();

  const zip = new AdmZip();

  zip.addFile("README.md", Buffer.from(buildClientReadme({ asset, project, analysis, generatedAt }), "utf8"));

  const pdfBytes = await buildMigrationPdf(asset, branding, {
    rulesOnly: analysis.llmUnavailable === true,
  });
  zip.addFile("executive-report.pdf", Buffer.from(pdfBytes));

  zip.addFile(
    "semantic-translation-log.json",
    Buffer.from(
      JSON.stringify(
        {
          assetId: asset.id,
          generatedAt,
          parserEngineVersion: analysis.parserEngineVersion,
          entryCount: (analysis.semanticTranslationLog ?? []).length,
          entries: analysis.semanticTranslationLog ?? [],
        },
        null,
        2,
      ),
      "utf8",
    ),
  );

  zip.addFile(
    "score-breakdown-and-pillars.json",
    Buffer.from(
      JSON.stringify(
        {
          assetId: asset.id,
          generatedAt,
          scoringEngineVersion: analysis.scoringEngineVersion,
          readinessScore: analysis.score,
          effort: analysis.effort,
          effortByWorkstream: analysis.effortByWorkstream ?? {},
          complexityTier: analysis.summary.calculationComplexityTier,
          complexityIndex: analysis.summary.calculationComplexityIndex,
          pillars: analysis.scoreCategories ?? [],
          scoreBreakdown: analysis.scoreBreakdown ?? [],
        },
        null,
        2,
      ),
      "utf8",
    ),
  );

  zip.addFile(
    "data-product-blueprint.json",
    Buffer.from(
      JSON.stringify(
        {
          assetId: asset.id,
          generatedAt,
          blueprint,
        },
        null,
        2,
      ),
      "utf8",
    ),
  );

  const snapshot = {
    assetId: asset.id,
    name: asset.name,
    createdAt: asset.createdAt,
    project: project
      ? {
          clientName: project.clientName,
          projectCode: project.projectCode,
          consultantOwner: project.consultantOwner,
          industry: project.industry,
        }
      : null,
    score: analysis.score,
    effort: analysis.effort,
    scoringEngineVersion: analysis.scoringEngineVersion,
    parserEngineVersion: analysis.parserEngineVersion,
    llmUnavailable: analysis.llmUnavailable ?? false,
    summary: analysis.summary,
    files: analysis.files,
    issues: analysis.issues,
    migrationPath: analysis.migrationPath,
    executiveSummary: analysis.executiveSummary,
    keyFindings: analysis.keyFindings,
    recommendations: analysis.recommendations,
    dataProductSuggestions: analysis.dataProductSuggestions,
  };
  zip.addFile("portfolio-snapshot.json", Buffer.from(JSON.stringify(snapshot, null, 2), "utf8"));

  if (analysis.trace?.prompt || analysis.trace?.response) {
    zip.addFile(
      "llm-audit.json",
      Buffer.from(
        JSON.stringify(
          {
            prompt: analysis.trace.prompt,
            response: analysis.trace.response,
            llmAuditEncryptedAtRest: asset.llmAuditEncrypted === 1,
          },
          null,
          2,
        ),
        "utf8",
      ),
    );
  }

  return {
    buffer: zip.toBuffer(),
    filename: `bdc-pulse-consulting-export-${asset.id}.zip`,
  };
}
