import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { PDFPage } from "pdf-lib";
import type { AssetRecord } from "@/db/schema";
import { embedLogoFromBase64 } from "@/lib/pdf-logo";
import { sanitizePdfText } from "@/lib/pdf-text";
import type {
  AnalysisIssue,
  AssetSummary,
  ParsedFileInsight,
  ScoreCategoryBreakdown,
  SemanticTranslationEntry,
} from "@/lib/types";

export type PdfBranding = {
  clientLabel?: string;
  companyName?: string;
  confidentialityFooter?: string;
  /** Raw or data-URL base64 (PNG/JPEG). Preferred over logoPngBytes. */
  logoBase64?: string;
  logoPngBytes?: Uint8Array;
};

export type PdfBuildOptions = {
  /** Emphasize deterministic / rule-based content only (no LLM narrative positioning). */
  rulesOnly?: boolean;
};

const SAP_BLUE = rgb(0.04, 0.43, 0.82);
const SAP_BLUE_DARK = rgb(0.03, 0.32, 0.62);
const SLATE_900 = rgb(0.06, 0.12, 0.22);
const SLATE_600 = rgb(0.35, 0.4, 0.48);
const PAGE_W = 842;
const PAGE_H = 595;

const DISCLAIMER =
  "Disclaimer: This report is generated by BDC Pulse using deterministic SAC JSON analysis. Migration Readiness Scores and pillar breakdowns are produced exclusively by a versioned rule engine and are not a guarantee of migration outcome, timeline, licensing, or financial results. Optional narrative text may be LLM-assisted when configured. All business and technical decisions remain with the customer and their implementation partners. Validate findings in workshops and against official SAP product documentation.";

const RULES_ONLY_BANNER =
  "Rules-only assessment - deterministic parser, weighted readiness pillars, and semantic translation log. No LLM narrative is required or included in this export variant.";

type ScoreBreakdownRow = { id: string; label: string; delta: number; detail: string };

function parseJson<T>(value: string | null | undefined, fallback: T): T {
  if (!value) return fallback;
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function parseScoreBreakdown(asset: AssetRecord): {
  version: string;
  parserVersion: string;
  breakdown: ScoreBreakdownRow[];
  categories: ScoreCategoryBreakdown[];
} {
  const raw = parseJson<unknown>(asset.scoreBreakdownJson, []);
  if (Array.isArray(raw)) {
    return {
      version: "",
      parserVersion: asset.parserEngineVersion ?? "",
      breakdown: raw as ScoreBreakdownRow[],
      categories: [],
    };
  }
  if (raw && typeof raw === "object" && "breakdown" in raw) {
    const o = raw as {
      version?: string;
      parserVersion?: string;
      breakdown?: ScoreBreakdownRow[];
      categories?: ScoreCategoryBreakdown[];
    };
    return {
      version: o.version ?? "",
      parserVersion: o.parserVersion ?? asset.parserEngineVersion ?? "",
      breakdown: Array.isArray(o.breakdown) ? o.breakdown : [],
      categories: Array.isArray(o.categories) ? o.categories : [],
    };
  }
  return { version: "", parserVersion: asset.parserEngineVersion ?? "", breakdown: [], categories: [] };
}

export async function buildMigrationPdf(
  asset: AssetRecord,
  branding?: PdfBranding,
  options?: PdfBuildOptions,
): Promise<Uint8Array> {
  const rulesOnly = options?.rulesOnly === true || asset.llmUnavailable === 1;
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const draw = (
    p: PDFPage,
    text: string,
    x: number,
    y: number,
    size = 11,
    isBold = false,
    color = SLATE_900,
  ) => {
    const safe = sanitizePdfText(text, isBold ? bold : font);
    p.drawText(safe, {
      x,
      y,
      size,
      font: isBold ? bold : font,
      color,
    });
  };

  const drawHeader = async (p: PDFPage, title: string, subtitle?: string) => {
    p.drawRectangle({ x: 0, y: PAGE_H - 56, width: PAGE_W, height: 56, color: SAP_BLUE });
    const org = (branding?.companyName?.trim() || "BDC Pulse").slice(0, 48);
    draw(p, org, 40, PAGE_H - 32, 14, true, rgb(1, 1, 1));
    if (subtitle) draw(p, subtitle, 40, PAGE_H - 48, 9, false, rgb(0.92, 0.95, 1));

    const logoB64 = branding?.logoBase64?.trim();
    if (logoB64) {
      const embedded = await embedLogoFromBase64(pdf, logoB64);
      if (embedded) {
        const maxW = 120;
        const maxH = 40;
        const scale = Math.min(maxW / embedded.width, maxH / embedded.height);
        const w = embedded.width * scale;
        const h = embedded.height * scale;
        p.drawRectangle({
          x: PAGE_W - w - 36,
          y: PAGE_H - 52,
          width: w + 12,
          height: h + 8,
          color: rgb(1, 1, 1),
          borderColor: rgb(0.85, 0.9, 0.95),
          borderWidth: 0.5,
        });
        p.drawImage(embedded.image, {
          x: PAGE_W - w - 42,
          y: PAGE_H - 48,
          width: w,
          height: h,
        });
      }
    } else if (branding?.logoPngBytes?.length) {
      const embedded = await embedLogoFromBase64(pdf, Buffer.from(branding.logoPngBytes).toString("base64"));
      if (embedded) {
        const maxW = 120;
        const scale = maxW / embedded.width;
        const w = maxW;
        const h = embedded.height * scale;
        p.drawRectangle({
          x: PAGE_W - w - 36,
          y: PAGE_H - 52,
          width: w + 12,
          height: h + 8,
          color: rgb(1, 1, 1),
        });
        p.drawImage(embedded.image, { x: PAGE_W - w - 42, y: PAGE_H - 48, width: w, height: h });
      }
    }

    draw(p, title, 40, PAGE_H - 72, 13, true, SLATE_900);
    if (subtitle) draw(p, subtitle, 40, PAGE_H - 86, 9, false, SLATE_600);
    p.drawLine({
      start: { x: 40, y: PAGE_H - 92 },
      end: { x: PAGE_W - 40, y: PAGE_H - 92 },
      thickness: 0.75,
      color: rgb(0.88, 0.9, 0.93),
    });
  };

  const drawFooter = (p: PDFPage, pageNum: number, total: number) => {
    const footer = branding?.confidentialityFooter ?? "CONFIDENTIAL - For authorized recipients only.";
    draw(p, footer, 40, 28, 7, false, SLATE_600);
    draw(p, `Page ${pageNum} of ${total}`, PAGE_W - 90, 28, 7, false, SLATE_600);
  };
  const wrapText = (text: string, maxChars: number) => {
    const words = text.replace(/\s+/g, " ").trim().split(" ");
    const lines: string[] = [];
    let current = "";
    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word;
      if (candidate.length <= maxChars) {
        current = candidate;
      } else {
        if (current) lines.push(current);
        current = word;
      }
    }
    if (current) lines.push(current);
    return lines;
  };
  const drawWrapped = (
    p: PDFPage,
    text: string,
    x: number,
    y: number,
    maxChars: number,
    size = 10,
    isBold = false,
  ) => {
    const lines = wrapText(text, maxChars);
    lines.forEach((line, idx) => draw(p, line, x, y - idx * (size + 4), size, isBold));
    return y - lines.length * (size + 4);
  };

  const { version, parserVersion, breakdown, categories } = parseScoreBreakdown(asset);
  const llmOff = rulesOnly || asset.llmUnavailable === 1;

  const summaryDefaults: AssetSummary = {
    stories: 0,
    models: 0,
    planningModels: 0,
    calculations: 0,
    dimensions: 0,
    measures: 0,
    pages: 0,
    widgets: 0,
    dataSources: 0,
    classicCharts: 0,
    liveConnections: 0,
    hasSemanticLayer: false,
    resultLookupHits: 0,
    restrictedMeasureHits: 0,
    exceptionAggregationHits: 0,
    planningLogicHits: 0,
    dataLockHits: 0,
    versionHits: 0,
    allocationHits: 0,
    reverseSignHits: 0,
    planningSequenceHits: 0,
    associationHits: 0,
    hierarchyHits: 0,
    calculationComplexityTier: "low",
    calculationComplexityIndex: 0,
  };
  const summary: AssetSummary = { ...summaryDefaults, ...parseJson<Partial<AssetSummary>>(asset.summaryJson, {}) };
  const files = parseJson<ParsedFileInsight[]>(asset.filesJson, []);
  const issues = parseJson<AnalysisIssue[]>(asset.issuesJson, []);
  const findings = parseJson<string[]>(asset.keyFindingsJson, []);
  const recommendations = parseJson<string[]>(asset.recommendationsJson, []);
  const path = parseJson<string[]>(asset.migrationPathJson, []);
  const translation = parseJson<SemanticTranslationEntry[]>(asset.semanticTranslationLogJson, []);
  const reportTitle = rulesOnly
    ? "Rules-only migration assessment"
    : "SAC to BDC / Datasphere migration assessment";

  const pages: PDFPage[] = [];

  const cover = pdf.addPage([PAGE_W, PAGE_H]);
  pages.push(cover);
  await drawHeader(cover, reportTitle, "Consultant-ready migration intelligence");
  let y = PAGE_H - 110;

  if (rulesOnly) {
    cover.drawRectangle({ x: 40, y: y - 36, width: PAGE_W - 80, height: 32, color: rgb(1, 0.97, 0.9), borderColor: rgb(0.9, 0.75, 0.2), borderWidth: 1 });
    y = drawWrapped(cover, RULES_ONLY_BANNER, 48, y - 8, 88, 8) - 44;
  }

  cover.drawRectangle({ x: 40, y: y - 88, width: 200, height: 88, color: rgb(0.94, 0.97, 1), borderColor: SAP_BLUE, borderWidth: 1.5 });
  draw(cover, "Migration Readiness", 52, y - 28, 10, false, SLATE_600);
  draw(cover, `${asset.score}%`, 52, y - 62, 28, true, SAP_BLUE_DARK);
  draw(cover, `Effort: ${asset.effort}`, 260, y - 48, 14, true);
  draw(cover, `Asset: ${asset.name}`, 260, y - 68, 10);
  if (branding?.clientLabel?.trim()) {
    draw(cover, branding.clientLabel, 260, y - 82, 9, false, SLATE_600);
  }
  y -= 108;
  const meta = `Generated ${new Date(asset.createdAt).toLocaleString("de-DE")} | Parser ${parserVersion || "-"} | Scoring ${version || "-"} | Complexity ${summary.calculationComplexityTier}`;
  y = drawWrapped(cover, meta, 40, y, 95, 8);
  if (!rulesOnly && asset.provider) {
    draw(cover, `LLM: ${asset.provider} / ${asset.model ?? "-"}`, 40, y - 12, 8, false, SLATE_600);
  } else if (llmOff) {
    draw(cover, "Assessment mode: deterministic rules only (LLM not used)", 40, y - 12, 8, false, SLATE_600);
  }

  const execPage = pdf.addPage([PAGE_W, PAGE_H]);
  pages.push(execPage);
  await drawHeader(execPage, "Executive summary & portfolio", asset.name);
  y = PAGE_H - 108;
  y = drawWrapped(execPage, asset.executiveSummary ?? "No executive summary available.", 40, y, 92, 10);
  y -= 16;
  draw(execPage, "Portfolio metrics", 40, y, 11, true);
  y -= 16;
  const metrics = [
    `Files: ${files.length} | Stories: ${summary.stories} | Models: ${summary.models} | Planning: ${summary.planningModels}`,
    `Pages: ${summary.pages} | Widgets: ${summary.widgets} | Data sources: ${summary.dataSources}`,
    `RESULTLOOKUP: ${summary.resultLookupHits} | Restricted: ${summary.restrictedMeasureHits} | Exception agg.: ${summary.exceptionAggregationHits}`,
    `Planning signals: ${summary.planningLogicHits} | Locks: ${summary.dataLockHits} | Versions: ${summary.versionHits}`,
  ];
  for (const line of metrics) y = drawWrapped(execPage, line, 40, y, 92, 9) - 6;

  if (issues.length > 0) {
    y -= 8;
    draw(execPage, "Key risk signals", 40, y, 11, true);
    y -= 14;
    for (const item of issues.slice(0, 6)) {
      y = drawWrapped(execPage, `* [${item.severity}] ${item.title}: ${item.recommendation}`, 40, y, 90, 8) - 8;
      if (y < 100) break;
    }
  }

  if (!rulesOnly && (findings.length > 0 || recommendations.length > 0)) {
    const narrPage = pdf.addPage([PAGE_W, PAGE_H]);
    pages.push(narrPage);
    await drawHeader(narrPage, "Findings & recommendations", "LLM-assisted narrative");
    y = PAGE_H - 108;
    draw(narrPage, "Findings", 40, y, 11, true);
    y -= 14;
    for (const f of findings.slice(0, 10)) {
      y = drawWrapped(narrPage, `* ${f}`, 40, y, 90, 9) - 6;
      if (y < 200) break;
    }
    y -= 10;
    draw(narrPage, "Recommendations", 40, y, 11, true);
    y -= 14;
    for (const r of recommendations.slice(0, 10)) {
      y = drawWrapped(narrPage, `* ${r}`, 40, y, 90, 9) - 6;
      if (y < 120) break;
    }
  }

  if (categories.length > 0 || breakdown.length > 0) {
    const scorePage = pdf.addPage([PAGE_W, PAGE_H]);
    pages.push(scorePage);
    await drawHeader(scorePage, "Weighted readiness score breakdown", "Deterministic pillars (25/25/20/15/15)");
    y = PAGE_H - 108;
    for (const cat of categories) {
      scorePage.drawRectangle({ x: 40, y: y - 52, width: PAGE_W - 80, height: 48, color: rgb(0.97, 0.98, 1), borderColor: rgb(0.9, 0.92, 0.96), borderWidth: 0.5 });
      draw(scorePage, `${cat.label} (${cat.weightPercent}%)`, 48, y - 12, 10, true);
      draw(scorePage, `Pillar score ${cat.pillarScore}/100 -> +${cat.weightedContribution} points`, 48, y - 26, 9);
      y = drawWrapped(scorePage, cat.detail, 48, y - 38, 88, 8) - 58;
    }
    y -= 8;
    draw(scorePage, "Audit trail", 40, y, 10, true);
    y -= 14;
    for (const row of breakdown) {
      y = drawWrapped(scorePage, `${row.label}: ${row.delta >= 0 ? "+" : ""}${row.delta}`, 40, y, 92, 8) - 6;
      if (y < 90) break;
    }
  }

  const translationSlice = translation.slice(0, 24);
  let tIdx = 0;
  while (tIdx < translationSlice.length) {
    const tPage = pdf.addPage([PAGE_W, PAGE_H]);
    pages.push(tPage);
    await drawHeader(tPage, "Semantic translation log", "SAC pattern -> BDC / Datasphere pattern");
    y = PAGE_H - 108;
    while (tIdx < translationSlice.length && y > 95) {
      const row = translationSlice[tIdx];
      tPage.drawRectangle({ x: 40, y: y - 72, width: PAGE_W - 80, height: 68, color: rgb(1, 1, 1), borderColor: rgb(0.88, 0.91, 0.95), borderWidth: 0.5 });
      draw(tPage, row.sacPattern ?? row.sacConcept, 48, y - 10, 9, true);
      draw(tPage, "->", 48, y - 22, 9, false, SAP_BLUE);
      y = drawWrapped(tPage, row.bdcPattern ?? row.datasphereTarget, 56, y - 24, 86, 9) - 2;
      y = drawWrapped(tPage, row.justification ?? row.transformation, 48, y - 36, 86, 7) - 2;
      if (row.recommendation) y = drawWrapped(tPage, `Action: ${row.recommendation}`, 48, y - 44, 86, 7) - 14;
      tIdx += 1;
      y -= 78;
    }
  }

  if (path.length > 0) {
    const pathPage = pdf.addPage([PAGE_W, PAGE_H]);
    pages.push(pathPage);
    await drawHeader(pathPage, "Recommended migration path", "Deterministic workstream order");
    y = PAGE_H - 108;
    path.forEach((step, idx) => {
      y = drawWrapped(pathPage, `${idx + 1}. ${step}`, 40, y, 92, 9) - 8;
    });
  }

  const legalPage = pdf.addPage([PAGE_W, PAGE_H]);
  pages.push(legalPage);
  await drawHeader(legalPage, "Disclaimer & methodology", "Legal notice");
  y = PAGE_H - 108;
  y = drawWrapped(legalPage, DISCLAIMER, 40, y, 92, 9);
  y -= 20;
  draw(legalPage, "Methodology", 40, y, 11, true);
  y -= 14;
  y = drawWrapped(
    legalPage,
    "Identical SAC JSON bytes and filenames produce identical parser counters and readiness scores for a given parser and scoring engine version. Weighted pillars compose the final 0-100 score; LLM output never alters numeric results.",
    40,
    y,
    92,
    9,
  );

  const total = pages.length;
  pages.forEach((p, i) => drawFooter(p, i + 1, total));

  return pdf.save();
}
